name: ras2fim
channels:
  - conda-forge
  - defaults
dependencies:
  - affine
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - blas
  - bottleneck
  - brotli
  - bzip2
  - ca-certificates
  - cached-property
  - certifi
  - cfitsio
  - click
  - click-plugins
  - cligj
  - curl
  - cycler
  - expat
  - fiona
  - fonttools
  - freetype
  - freexl
  - gdal=3
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - h5netcdf
  - h5py
  - hdf4
  - hdf5
  - icc_rt
  - intel-openmp
  - joblib
  - jpeg
  - kealib
  - kiwisolver
  - krb5
  - libcurl
  - libgdal
  - libiconv
  - libnetcdf
  - libpng
  - libpq
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libxml2
  - lz4-c
  - m2w64-expat
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gettext
  - m2w64-gmp
  - m2w64-libiconv
  - m2w64-libwinpthread-git
  - m2w64-xz
  - mapclassify
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - munch
  - munkres
  - networkx
  - numexpr
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - pandas
  - pillow
  - pip
  - postgresql
  - proj=6
  - pyparsing
  - pyproj
  - pyreadline
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - rasterio=1
  - rioxarray
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snuggs
  - sqlite
  - threadpoolctl
  - tiledb
  - tk
  - tornado
  - tqdm
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - xarray
  - xerces-c
  - xz
  - zlib
  - zstd